var dir_1e142f69c0d1c62a2fe3d3319112ca90 =
[
    [ "Alternative Configurations", "dir_4d017de6c0cf602276e0121a660ee06d.html", "dir_4d017de6c0cf602276e0121a660ee06d" ],
    [ "project.X", "dir_3371984377a8c0758c6113d9067b2b4a.html", "dir_3371984377a8c0758c6113d9067b2b4a" ],
    [ "generic_processorConfigBits.h", "generic__processor_config_bits_8h.html", "generic__processor_config_bits_8h" ],
    [ "main.c", "m_touch_cap_2_p_i_c12_f_01_p_i_c16_f_01_library_2_main_8c.html", null ],
    [ "mComm.c", "m_comm_8c.html", "m_comm_8c" ],
    [ "mComm.h", "m_comm_8h.html", "m_comm_8h" ],
    [ "mComm_config.h", "m_comm__config_8h.html", null ],
    [ "mComm_custom.c", "m_comm__custom_8c.html", "m_comm__custom_8c" ],
    [ "mComm_opcodes.c", "m_comm__opcodes_8c.html", "m_comm__opcodes_8c" ],
    [ "mComm_optionsForConfig.h", "m_comm__options_for_config_8h.html", null ],
    [ "mComm_processConfiguration.h", "m_comm__process_configuration_8h.html", null ],
    [ "mTouch.c", "m_touch_8c.html", "m_touch_8c" ],
    [ "mTouch.h", "m_touch_cap_2_p_i_c12_f_01_p_i_c16_f_01_library_2m_touch_8h.html", "m_touch_cap_2_p_i_c12_f_01_p_i_c16_f_01_library_2m_touch_8h" ],
    [ "mTouch_acquisition.c", "m_touch__acquisition_8c.html", "m_touch__acquisition_8c" ],
    [ "mTouch_acquisition_HCVD.c", "m_touch__acquisition___h_c_v_d_8c.html", "m_touch__acquisition___h_c_v_d_8c" ],
    [ "mTouch_config.h", "m_touch__config_8h.html", null ],
    [ "mTouch_config_cvdAdvanced.h", "m_touch__config__cvd_advanced_8h.html", null ],
    [ "mTouch_config_modes.h", "m_touch__config__modes_8h.html", null ],
    [ "mTouch_config_slider.h", "m_touch__config__slider_8h.html", null ],
    [ "mTouch_documentation.h", "m_touch__documentation_8h.html", null ],
    [ "mTouch_eeprom.c", "m_touch__eeprom_8c.html", "m_touch__eeprom_8c" ],
    [ "mTouch_eeprom.h", "m_touch__eeprom_8h.html", "m_touch__eeprom_8h" ],
    [ "mTouch_macroLibrary_common.h", "m_touch__macro_library__common_8h.html", null ],
    [ "mTouch_modes.h", "m_touch__modes_8h.html", null ],
    [ "mTouch_optionsForConfig.h", "m_touch__options_for_config_8h.html", null ],
    [ "mTouch_processConfiguration.h", "m_touch__process_configuration_8h.html", null ],
    [ "mTouch_proximity.c", "m_touch__proximity_8c.html", "m_touch__proximity_8c" ],
    [ "mTouch_proximity.h", "m_touch__proximity_8h.html", "m_touch__proximity_8h" ],
    [ "mTouch_slider.c", "m_touch__slider_8c.html", "m_touch__slider_8c" ],
    [ "mTouch_slider.h", "m_touch__slider_8h.html", "m_touch__slider_8h" ],
    [ "mTouchCVD_macroLibrary_PIC16F.h", "m_touch_c_v_d__macro_library___p_i_c16_f_8h.html", null ],
    [ "mTouchCVD_macroLibrary_PIC16F1.h", "m_touch_c_v_d__macro_library___p_i_c16_f1_8h.html", null ],
    [ "mTouchCVD_macroLibrary_PIC18F.h", "m_touch_c_v_d__macro_library___p_i_c18_f_8h.html", null ]
];